artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/48594250d1474275baba93c736a4aca9/artifacts
end_time: 1673465709585
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 48594250d1474275baba93c736a4aca9
run_uuid: 48594250d1474275baba93c736a4aca9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465709443
status: 3
tags: []
user_id: fatsk
