artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/eb7ffb595bc047a7b4b32bbf816c202d/artifacts
end_time: 1673465732227
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: eb7ffb595bc047a7b4b32bbf816c202d
run_uuid: eb7ffb595bc047a7b4b32bbf816c202d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465732175
status: 3
tags: []
user_id: fatsk
