artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/516aa2bc6b93411694c209616143fac9/artifacts
end_time: 1673442200371
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 516aa2bc6b93411694c209616143fac9
run_uuid: 516aa2bc6b93411694c209616143fac9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442200328
status: 3
tags: []
user_id: fatsk
