artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/ca94a62b62f648f19e7a3bc0b690bb9e/artifacts
end_time: 1673441931453
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ca94a62b62f648f19e7a3bc0b690bb9e
run_uuid: ca94a62b62f648f19e7a3bc0b690bb9e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441931400
status: 3
tags: []
user_id: fatsk
