artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/1f710cf42e18442e97f237bda77ae759/artifacts
end_time: 1673465712071
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 1f710cf42e18442e97f237bda77ae759
run_uuid: 1f710cf42e18442e97f237bda77ae759
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465712024
status: 3
tags: []
user_id: fatsk
