artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/62a69968e2a742be9af59ea728b0c06e/artifacts
end_time: 1673441939972
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 62a69968e2a742be9af59ea728b0c06e
run_uuid: 62a69968e2a742be9af59ea728b0c06e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441939911
status: 3
tags: []
user_id: fatsk
