artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/fd206182e4c945ceb4e1dde0012df29a/artifacts
end_time: 1673442031186
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fd206182e4c945ceb4e1dde0012df29a
run_uuid: fd206182e4c945ceb4e1dde0012df29a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442031045
status: 3
tags: []
user_id: fatsk
