artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/82d5cf5f72de468c8b668b77edb09748/artifacts
end_time: 1673465729609
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 82d5cf5f72de468c8b668b77edb09748
run_uuid: 82d5cf5f72de468c8b668b77edb09748
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465729557
status: 3
tags: []
user_id: fatsk
