artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/9a1821061f9a4d7c85352ef12a0c8e0c/artifacts
end_time: 1673442361858
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9a1821061f9a4d7c85352ef12a0c8e0c
run_uuid: 9a1821061f9a4d7c85352ef12a0c8e0c
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442361719
status: 3
tags: []
user_id: fatsk
