artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/effb750bcfe94a1e9b09c08eede113c3/artifacts
end_time: 1673465972732
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: effb750bcfe94a1e9b09c08eede113c3
run_uuid: effb750bcfe94a1e9b09c08eede113c3
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465972682
status: 3
tags: []
user_id: fatsk
