artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/43ca83513c5d44e6a5f7052bb55aa0bd/artifacts
end_time: 1673465723442
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 43ca83513c5d44e6a5f7052bb55aa0bd
run_uuid: 43ca83513c5d44e6a5f7052bb55aa0bd
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465723394
status: 3
tags: []
user_id: fatsk
