artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/e3951bd401124c1390f2d1733aa8f8a6/artifacts
end_time: 1673442316515
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e3951bd401124c1390f2d1733aa8f8a6
run_uuid: e3951bd401124c1390f2d1733aa8f8a6
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442316379
status: 3
tags: []
user_id: fatsk
