artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/6ddc5e7d187a4f05ac8006bf7dbff22a/artifacts
end_time: 1673442425362
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 6ddc5e7d187a4f05ac8006bf7dbff22a
run_uuid: 6ddc5e7d187a4f05ac8006bf7dbff22a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442425229
status: 3
tags: []
user_id: fatsk
