artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/3280e8a55ccf478992d9d68e2521da31/artifacts
end_time: 1673441996115
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3280e8a55ccf478992d9d68e2521da31
run_uuid: 3280e8a55ccf478992d9d68e2521da31
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441996071
status: 3
tags: []
user_id: fatsk
