artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/646da51ce11f4f67b4fe8d9ef41d8287/artifacts
end_time: 1673465915279
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 646da51ce11f4f67b4fe8d9ef41d8287
run_uuid: 646da51ce11f4f67b4fe8d9ef41d8287
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465915232
status: 3
tags: []
user_id: fatsk
