artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/d583bf9b7aaa4913a560da02836efa76/artifacts
end_time: 1673465806406
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d583bf9b7aaa4913a560da02836efa76
run_uuid: d583bf9b7aaa4913a560da02836efa76
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465806256
status: 3
tags: []
user_id: fatsk
