artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/f591200863a1461e8cdfa83494bb8be2/artifacts
end_time: 1673442232555
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f591200863a1461e8cdfa83494bb8be2
run_uuid: f591200863a1461e8cdfa83494bb8be2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442232419
status: 3
tags: []
user_id: fatsk
