artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/14af965e1f1844f2b8e2aff2cdb7d24b/artifacts
end_time: 1673465888318
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 14af965e1f1844f2b8e2aff2cdb7d24b
run_uuid: 14af965e1f1844f2b8e2aff2cdb7d24b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465888247
status: 3
tags: []
user_id: fatsk
