artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/00b713c51d8147bfa30a1276f5b6b4a9/artifacts
end_time: 1673442355564
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 00b713c51d8147bfa30a1276f5b6b4a9
run_uuid: 00b713c51d8147bfa30a1276f5b6b4a9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442355433
status: 3
tags: []
user_id: fatsk
