artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/f5d2c00631834eb0a91b0b2cd624eeef/artifacts
end_time: 1673442226323
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f5d2c00631834eb0a91b0b2cd624eeef
run_uuid: f5d2c00631834eb0a91b0b2cd624eeef
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442226170
status: 3
tags: []
user_id: fatsk
