artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/3b6ce6f00ca940d0bcfc05d01549cf8f/artifacts
end_time: 1673465932357
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3b6ce6f00ca940d0bcfc05d01549cf8f
run_uuid: 3b6ce6f00ca940d0bcfc05d01549cf8f
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465932309
status: 3
tags: []
user_id: fatsk
