artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/a089c1979a754cc7bb30650a7987a31f/artifacts
end_time: 1673442002876
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a089c1979a754cc7bb30650a7987a31f
run_uuid: a089c1979a754cc7bb30650a7987a31f
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442002835
status: 3
tags: []
user_id: fatsk
