artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/47f336f2f0f842168eeb860911c4e634/artifacts
end_time: 1673441942761
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 47f336f2f0f842168eeb860911c4e634
run_uuid: 47f336f2f0f842168eeb860911c4e634
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441942721
status: 3
tags: []
user_id: fatsk
