artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/f3b8f13b3a7548d0868608b46dc59f6a/artifacts
end_time: 1673465962918
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f3b8f13b3a7548d0868608b46dc59f6a
run_uuid: f3b8f13b3a7548d0868608b46dc59f6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465962871
status: 3
tags: []
user_id: fatsk
