artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/b14afaf7d8844a69afd8fa9cb63e0473/artifacts
end_time: 1673442334936
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b14afaf7d8844a69afd8fa9cb63e0473
run_uuid: b14afaf7d8844a69afd8fa9cb63e0473
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442334823
status: 3
tags: []
user_id: fatsk
