artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/a35b0626b26d4cdaa024742c1ddf5577/artifacts
end_time: 1673442248785
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a35b0626b26d4cdaa024742c1ddf5577
run_uuid: a35b0626b26d4cdaa024742c1ddf5577
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442248652
status: 3
tags: []
user_id: fatsk
