artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/1272769f843a485da3c97c6bc3607c46/artifacts
end_time: 1673465730677
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 1272769f843a485da3c97c6bc3607c46
run_uuid: 1272769f843a485da3c97c6bc3607c46
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465730628
status: 3
tags: []
user_id: fatsk
