artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/687d48a870ec486daa9918c06017b3a0/artifacts
end_time: 1673465733435
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 687d48a870ec486daa9918c06017b3a0
run_uuid: 687d48a870ec486daa9918c06017b3a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465733387
status: 3
tags: []
user_id: fatsk
