artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/38ea5174a13c4c2b8cac21c5a639e8ba/artifacts
end_time: 1673442020748
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 38ea5174a13c4c2b8cac21c5a639e8ba
run_uuid: 38ea5174a13c4c2b8cac21c5a639e8ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442020697
status: 3
tags: []
user_id: fatsk
