artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/d7193541225c41e9a0cb6c034eedb3b1/artifacts
end_time: 1673465840957
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d7193541225c41e9a0cb6c034eedb3b1
run_uuid: d7193541225c41e9a0cb6c034eedb3b1
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465840890
status: 3
tags: []
user_id: fatsk
