artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/81af19b7cc164f11a055a3d29ea839d3/artifacts
end_time: 1673465769260
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 81af19b7cc164f11a055a3d29ea839d3
run_uuid: 81af19b7cc164f11a055a3d29ea839d3
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465769195
status: 3
tags: []
user_id: fatsk
