artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/b6c661380885408295fbae43e79ee133/artifacts
end_time: 1673442087458
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b6c661380885408295fbae43e79ee133
run_uuid: b6c661380885408295fbae43e79ee133
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442087406
status: 3
tags: []
user_id: fatsk
