artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/b4beedfe6de44a8a9745317829f73de9/artifacts
end_time: 1673465870565
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: b4beedfe6de44a8a9745317829f73de9
run_uuid: b4beedfe6de44a8a9745317829f73de9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465870405
status: 3
tags: []
user_id: fatsk
