artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/9d109f96b1c54f2ba22e95a7a72fe05b/artifacts
end_time: 1673465846508
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9d109f96b1c54f2ba22e95a7a72fe05b
run_uuid: 9d109f96b1c54f2ba22e95a7a72fe05b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465846446
status: 3
tags: []
user_id: fatsk
