artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/78057b2f2fb9466a8c17a4b176e97db9/artifacts
end_time: 1673442065210
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 78057b2f2fb9466a8c17a4b176e97db9
run_uuid: 78057b2f2fb9466a8c17a4b176e97db9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442065169
status: 3
tags: []
user_id: fatsk
