artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/afec86bce4644521a8382bee5063dd12/artifacts
end_time: 1673465917095
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: afec86bce4644521a8382bee5063dd12
run_uuid: afec86bce4644521a8382bee5063dd12
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465917042
status: 3
tags: []
user_id: fatsk
