artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/d2d2c9dc125c440d8e1e429a56f048f5/artifacts
end_time: 1673442158000
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: d2d2c9dc125c440d8e1e429a56f048f5
run_uuid: d2d2c9dc125c440d8e1e429a56f048f5
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442157958
status: 3
tags: []
user_id: fatsk
