artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/98654fc11e8f433aaa9fcd67a3b562e2/artifacts
end_time: 1673465978096
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 98654fc11e8f433aaa9fcd67a3b562e2
run_uuid: 98654fc11e8f433aaa9fcd67a3b562e2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465978048
status: 3
tags: []
user_id: fatsk
