artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/a3f17ba52c1d4064a6e56e0b125518ce/artifacts
end_time: 1673465918017
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a3f17ba52c1d4064a6e56e0b125518ce
run_uuid: a3f17ba52c1d4064a6e56e0b125518ce
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465917970
status: 3
tags: []
user_id: fatsk
