artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/44d6dfaceb104e67aa3e3550f0e6c00c/artifacts
end_time: 1673442091802
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 44d6dfaceb104e67aa3e3550f0e6c00c
run_uuid: 44d6dfaceb104e67aa3e3550f0e6c00c
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442091758
status: 3
tags: []
user_id: fatsk
