artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/a2d45c696a884100926a3d987b3b8d8e/artifacts
end_time: 1673465732955
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a2d45c696a884100926a3d987b3b8d8e
run_uuid: a2d45c696a884100926a3d987b3b8d8e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465732908
status: 3
tags: []
user_id: fatsk
