artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/deb1035589834c9cba74a692627e055d/artifacts
end_time: 1673465721109
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: deb1035589834c9cba74a692627e055d
run_uuid: deb1035589834c9cba74a692627e055d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465721061
status: 3
tags: []
user_id: fatsk
