artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/b2cac1b006ac47da8f4717d35f730af0/artifacts
end_time: 1673442302505
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b2cac1b006ac47da8f4717d35f730af0
run_uuid: b2cac1b006ac47da8f4717d35f730af0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442302369
status: 3
tags: []
user_id: fatsk
