artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/fac48c36cce5480e83c22ecc2b61377f/artifacts
end_time: 1673465962042
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: fac48c36cce5480e83c22ecc2b61377f
run_uuid: fac48c36cce5480e83c22ecc2b61377f
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465961988
status: 3
tags: []
user_id: fatsk
