artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/c19c0113ef0940ee893e436ebdca3117/artifacts
end_time: 1673442291137
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c19c0113ef0940ee893e436ebdca3117
run_uuid: c19c0113ef0940ee893e436ebdca3117
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442291008
status: 3
tags: []
user_id: fatsk
