artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/461ff25f576c4adaa3893c7c2e43483e/artifacts
end_time: 1673442098406
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 461ff25f576c4adaa3893c7c2e43483e
run_uuid: 461ff25f576c4adaa3893c7c2e43483e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442098362
status: 3
tags: []
user_id: fatsk
