artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/46bd921e809a4f48a5a8bcb8434fe96f/artifacts
end_time: 1673465722819
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 46bd921e809a4f48a5a8bcb8434fe96f
run_uuid: 46bd921e809a4f48a5a8bcb8434fe96f
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465722766
status: 3
tags: []
user_id: fatsk
