artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/05ef3e5a9bf44b1cb55060d338a2a62e/artifacts
end_time: 1673442012312
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 05ef3e5a9bf44b1cb55060d338a2a62e
run_uuid: 05ef3e5a9bf44b1cb55060d338a2a62e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442012267
status: 3
tags: []
user_id: fatsk
