artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/681c4aa77e404d85a829bd14d1bc5451/artifacts
end_time: 1673465783173
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 681c4aa77e404d85a829bd14d1bc5451
run_uuid: 681c4aa77e404d85a829bd14d1bc5451
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465783077
status: 3
tags: []
user_id: fatsk
