artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/1fc6e06ff57c4bcb9f691c970ba0b58d/artifacts
end_time: 1673442412630
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1fc6e06ff57c4bcb9f691c970ba0b58d
run_uuid: 1fc6e06ff57c4bcb9f691c970ba0b58d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442412566
status: 3
tags: []
user_id: fatsk
