artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/6ab623deb6b24a57a2d405f638f41aad/artifacts
end_time: 1673465820338
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 6ab623deb6b24a57a2d405f638f41aad
run_uuid: 6ab623deb6b24a57a2d405f638f41aad
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465820265
status: 3
tags: []
user_id: fatsk
