artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/ea8d0c27e7684a9d8d8a2b0748be2d60/artifacts
end_time: 1673442077404
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ea8d0c27e7684a9d8d8a2b0748be2d60
run_uuid: ea8d0c27e7684a9d8d8a2b0748be2d60
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442077271
status: 3
tags: []
user_id: fatsk
