artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/e47d0481579c423988ae57cbcea7873c/artifacts
end_time: 1673442103878
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e47d0481579c423988ae57cbcea7873c
run_uuid: e47d0481579c423988ae57cbcea7873c
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442103840
status: 3
tags: []
user_id: fatsk
