artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/f91af06a5f1748199c382361141bf2f7/artifacts
end_time: 1673441894003
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f91af06a5f1748199c382361141bf2f7
run_uuid: f91af06a5f1748199c382361141bf2f7
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441893943
status: 3
tags: []
user_id: fatsk
