artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/f58669b44e7f4acfa3b890e0185db178/artifacts
end_time: 1673441996704
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f58669b44e7f4acfa3b890e0185db178
run_uuid: f58669b44e7f4acfa3b890e0185db178
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441996664
status: 3
tags: []
user_id: fatsk
