artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/493bcba1f6824045892b11d4ab01e598/artifacts
end_time: 1673465787701
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 493bcba1f6824045892b11d4ab01e598
run_uuid: 493bcba1f6824045892b11d4ab01e598
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465787552
status: 3
tags: []
user_id: fatsk
