artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/fe49120026024ce7a19aad69f2ca3e0d/artifacts
end_time: 1673442118445
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fe49120026024ce7a19aad69f2ca3e0d
run_uuid: fe49120026024ce7a19aad69f2ca3e0d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442118399
status: 3
tags: []
user_id: fatsk
