artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/30d47165a36d46dd988374eb0f258f51/artifacts
end_time: 1673441912937
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 30d47165a36d46dd988374eb0f258f51
run_uuid: 30d47165a36d46dd988374eb0f258f51
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441912798
status: 3
tags: []
user_id: fatsk
