artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/f853e1237fa64f2c9ab46ae7c853d391/artifacts
end_time: 1673465740386
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f853e1237fa64f2c9ab46ae7c853d391
run_uuid: f853e1237fa64f2c9ab46ae7c853d391
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465740333
status: 3
tags: []
user_id: fatsk
