artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/f97e05c71fc048d1b0559d1df61b81df/artifacts
end_time: 1673465672681
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f97e05c71fc048d1b0559d1df61b81df
run_uuid: f97e05c71fc048d1b0559d1df61b81df
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465672627
status: 3
tags: []
user_id: fatsk
