artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/31d6b554375c481491a0a4a0c062ccff/artifacts
end_time: 1673465706616
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 31d6b554375c481491a0a4a0c062ccff
run_uuid: 31d6b554375c481491a0a4a0c062ccff
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465706569
status: 3
tags: []
user_id: fatsk
