artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/faea13a622c54e01a89e7ea4439b9036/artifacts
end_time: 1673465845499
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: faea13a622c54e01a89e7ea4439b9036
run_uuid: faea13a622c54e01a89e7ea4439b9036
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465845350
status: 3
tags: []
user_id: fatsk
