artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/bda13a3bfeda4ad78b3d4d0d17c26d62/artifacts
end_time: 1673442138149
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: bda13a3bfeda4ad78b3d4d0d17c26d62
run_uuid: bda13a3bfeda4ad78b3d4d0d17c26d62
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442138107
status: 3
tags: []
user_id: fatsk
