artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/9f1febe05d4c4dd7a96f9d28152d13f2/artifacts
end_time: 1673442057656
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9f1febe05d4c4dd7a96f9d28152d13f2
run_uuid: 9f1febe05d4c4dd7a96f9d28152d13f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442057526
status: 3
tags: []
user_id: fatsk
