artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/e4c2db858cbc4d7691c0338d37daf7fd/artifacts
end_time: 1673465708004
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e4c2db858cbc4d7691c0338d37daf7fd
run_uuid: e4c2db858cbc4d7691c0338d37daf7fd
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465707956
status: 3
tags: []
user_id: fatsk
