artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/3a5e347c8d7f48af93e06bcb9b49c94b/artifacts
end_time: 1673465773855
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3a5e347c8d7f48af93e06bcb9b49c94b
run_uuid: 3a5e347c8d7f48af93e06bcb9b49c94b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465773706
status: 3
tags: []
user_id: fatsk
