artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/9fa0cc5b576f4748b7a7d6ed9407867b/artifacts
end_time: 1673442278762
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9fa0cc5b576f4748b7a7d6ed9407867b
run_uuid: 9fa0cc5b576f4748b7a7d6ed9407867b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442278629
status: 3
tags: []
user_id: fatsk
