artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/d209d426348c4bf3aef91c0cc4304a52/artifacts
end_time: 1673465885205
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d209d426348c4bf3aef91c0cc4304a52
run_uuid: d209d426348c4bf3aef91c0cc4304a52
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465885054
status: 3
tags: []
user_id: fatsk
