artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/a95bd2420d1a48feb220f5ab3d1948bb/artifacts
end_time: 1673465726178
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a95bd2420d1a48feb220f5ab3d1948bb
run_uuid: a95bd2420d1a48feb220f5ab3d1948bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465726132
status: 3
tags: []
user_id: fatsk
