artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/d11d0bccb5e84b59a5e7a96f32eae1b8/artifacts
end_time: 1673442366915
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: d11d0bccb5e84b59a5e7a96f32eae1b8
run_uuid: d11d0bccb5e84b59a5e7a96f32eae1b8
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442366781
status: 3
tags: []
user_id: fatsk
