artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/743e694e4c1b4e9890dee0da4f2bf0d2/artifacts
end_time: 1673442205242
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 743e694e4c1b4e9890dee0da4f2bf0d2
run_uuid: 743e694e4c1b4e9890dee0da4f2bf0d2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442205203
status: 3
tags: []
user_id: fatsk
