artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/50678abfd6a449159ddedc3aab5f2ff2/artifacts
end_time: 1673442144263
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 50678abfd6a449159ddedc3aab5f2ff2
run_uuid: 50678abfd6a449159ddedc3aab5f2ff2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442144222
status: 3
tags: []
user_id: fatsk
