artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/c9306d488fc44410b1d7b0ad713159d9/artifacts
end_time: 1673465720545
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c9306d488fc44410b1d7b0ad713159d9
run_uuid: c9306d488fc44410b1d7b0ad713159d9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465720498
status: 3
tags: []
user_id: fatsk
