artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/0ff59823aeb44f1a935e41a7cd697771/artifacts
end_time: 1673442040228
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 0ff59823aeb44f1a935e41a7cd697771
run_uuid: 0ff59823aeb44f1a935e41a7cd697771
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442040091
status: 3
tags: []
user_id: fatsk
