artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/78d775b3c6f641b2b51413032c201da9/artifacts
end_time: 1673442008619
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 78d775b3c6f641b2b51413032c201da9
run_uuid: 78d775b3c6f641b2b51413032c201da9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442008578
status: 3
tags: []
user_id: fatsk
