artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/1ef20b534dd9442c96e23e02c8863e05/artifacts
end_time: 1673441901840
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1ef20b534dd9442c96e23e02c8863e05
run_uuid: 1ef20b534dd9442c96e23e02c8863e05
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441901780
status: 3
tags: []
user_id: fatsk
