artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/5c56ea1f87d34624a96f3e31e2885aee/artifacts
end_time: 1673442025058
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5c56ea1f87d34624a96f3e31e2885aee
run_uuid: 5c56ea1f87d34624a96f3e31e2885aee
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442024997
status: 3
tags: []
user_id: fatsk
