artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/aad494e325014b04a79d9f66a6afac8e/artifacts
end_time: 1673465901668
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: aad494e325014b04a79d9f66a6afac8e
run_uuid: aad494e325014b04a79d9f66a6afac8e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465901572
status: 3
tags: []
user_id: fatsk
