artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/fd67172fa7ef485cb980e655932cfd84/artifacts
end_time: 1673441930587
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fd67172fa7ef485cb980e655932cfd84
run_uuid: fd67172fa7ef485cb980e655932cfd84
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441930524
status: 3
tags: []
user_id: fatsk
