artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/9f88ceb57d364f6fbd981bfc63d38651/artifacts
end_time: 1673465897350
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9f88ceb57d364f6fbd981bfc63d38651
run_uuid: 9f88ceb57d364f6fbd981bfc63d38651
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465897201
status: 3
tags: []
user_id: fatsk
