artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/54e9559709424ec88d5b52de2d7dc7e1/artifacts
end_time: 1673442349439
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 54e9559709424ec88d5b52de2d7dc7e1
run_uuid: 54e9559709424ec88d5b52de2d7dc7e1
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442349382
status: 3
tags: []
user_id: fatsk
