artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/1/d177fd0a47d54547a12c08b13869ae12/artifacts
end_time: 1673461535596
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d177fd0a47d54547a12c08b13869ae12
run_uuid: d177fd0a47d54547a12c08b13869ae12
source_name: ''
source_type: 4
source_version: ''
start_time: 1673461528776
status: 3
tags: []
user_id: fatsk
