artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/2d1bd9e8e7f247569a4c0a0e0d963568/artifacts
end_time: 1673442015119
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2d1bd9e8e7f247569a4c0a0e0d963568
run_uuid: 2d1bd9e8e7f247569a4c0a0e0d963568
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442014988
status: 3
tags: []
user_id: fatsk
