artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/ca28620fa6de4c9fb83c96ed26b2a84e/artifacts
end_time: 1673465736365
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ca28620fa6de4c9fb83c96ed26b2a84e
run_uuid: ca28620fa6de4c9fb83c96ed26b2a84e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465736315
status: 3
tags: []
user_id: fatsk
