artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/b9c961714a8540b89ec9f6435cd0fb59/artifacts
end_time: 1673441987314
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b9c961714a8540b89ec9f6435cd0fb59
run_uuid: b9c961714a8540b89ec9f6435cd0fb59
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441987263
status: 3
tags: []
user_id: fatsk
