artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/07e66ec049e842828bd247dc1f06c3cf/artifacts
end_time: 1673442094575
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 07e66ec049e842828bd247dc1f06c3cf
run_uuid: 07e66ec049e842828bd247dc1f06c3cf
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442094532
status: 3
tags: []
user_id: fatsk
