artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/6b42ffea4e7f4515a7bfe9b24b82e5eb/artifacts
end_time: 1673442392473
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 6b42ffea4e7f4515a7bfe9b24b82e5eb
run_uuid: 6b42ffea4e7f4515a7bfe9b24b82e5eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442392404
status: 3
tags: []
user_id: fatsk
