artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/02a165845fff4d61a82ea5d49b7d15da/artifacts
end_time: 1673442255087
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 02a165845fff4d61a82ea5d49b7d15da
run_uuid: 02a165845fff4d61a82ea5d49b7d15da
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442254952
status: 3
tags: []
user_id: fatsk
