artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/0589ee55f20e4e4ea388b3cc859032ec/artifacts
end_time: 1673465893060
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 0589ee55f20e4e4ea388b3cc859032ec
run_uuid: 0589ee55f20e4e4ea388b3cc859032ec
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465892913
status: 3
tags: []
user_id: fatsk
