artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/f12f0a6aabd24bde8f42ffc782346ac9/artifacts
end_time: 1673442405151
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f12f0a6aabd24bde8f42ffc782346ac9
run_uuid: f12f0a6aabd24bde8f42ffc782346ac9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442405016
status: 3
tags: []
user_id: fatsk
