artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/d15f6f4b3d314dcba6e379734eb3027a/artifacts
end_time: 1673442150528
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: d15f6f4b3d314dcba6e379734eb3027a
run_uuid: d15f6f4b3d314dcba6e379734eb3027a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442150328
status: 3
tags: []
user_id: fatsk
