artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/a16c2d949e4b4265939392f0cbec6ca0/artifacts
end_time: 1673442164191
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a16c2d949e4b4265939392f0cbec6ca0
run_uuid: a16c2d949e4b4265939392f0cbec6ca0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442164150
status: 3
tags: []
user_id: fatsk
