artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/27eb39b4dda24af4a69a3122c859dae1/artifacts
end_time: 1673442386103
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 27eb39b4dda24af4a69a3122c859dae1
run_uuid: 27eb39b4dda24af4a69a3122c859dae1
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442385953
status: 3
tags: []
user_id: fatsk
