artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/740660aa8e474fbda77ca53d9be9f6ae/artifacts
end_time: 1673465861335
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 740660aa8e474fbda77ca53d9be9f6ae
run_uuid: 740660aa8e474fbda77ca53d9be9f6ae
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465861185
status: 3
tags: []
user_id: fatsk
