artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/f3e44e2b94434266ad912966b9f54db9/artifacts
end_time: 1673441961703
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f3e44e2b94434266ad912966b9f54db9
run_uuid: f3e44e2b94434266ad912966b9f54db9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441961661
status: 3
tags: []
user_id: fatsk
