artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/85b49196736d4ccd9692156deabec6d3/artifacts
end_time: 1673465759158
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 85b49196736d4ccd9692156deabec6d3
run_uuid: 85b49196736d4ccd9692156deabec6d3
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465759003
status: 3
tags: []
user_id: fatsk
