artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/01a6d0ec60fa40f4935ff66b88775de0/artifacts
end_time: 1673465875048
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 01a6d0ec60fa40f4935ff66b88775de0
run_uuid: 01a6d0ec60fa40f4935ff66b88775de0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465874908
status: 3
tags: []
user_id: fatsk
