artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/0b20bf96e921471ca91f8492b31de798/artifacts
end_time: 1673442049145
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 0b20bf96e921471ca91f8492b31de798
run_uuid: 0b20bf96e921471ca91f8492b31de798
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442049085
status: 3
tags: []
user_id: fatsk
