artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/53d2fe3ad4e2493f90ac4f624630b1a0/artifacts
end_time: 1673465839986
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 53d2fe3ad4e2493f90ac4f624630b1a0
run_uuid: 53d2fe3ad4e2493f90ac4f624630b1a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465839920
status: 3
tags: []
user_id: fatsk
