artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/361c9459817e4fe2942fa6a02b0aa080/artifacts
end_time: 1673465801687
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 361c9459817e4fe2942fa6a02b0aa080
run_uuid: 361c9459817e4fe2942fa6a02b0aa080
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465801533
status: 3
tags: []
user_id: fatsk
