artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/538baf8ad73545469c5d2796442a33c4/artifacts
end_time: 1673465910159
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 538baf8ad73545469c5d2796442a33c4
run_uuid: 538baf8ad73545469c5d2796442a33c4
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465910103
status: 3
tags: []
user_id: fatsk
