artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/84d48fcfa8de4094b9ed4e329dc7f5b6/artifacts
end_time: 1673442218840
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 84d48fcfa8de4094b9ed4e329dc7f5b6
run_uuid: 84d48fcfa8de4094b9ed4e329dc7f5b6
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442218801
status: 3
tags: []
user_id: fatsk
