artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/28586f3a9b6747bbbb7acc339de4b728/artifacts
end_time: 1673442024688
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 28586f3a9b6747bbbb7acc339de4b728
run_uuid: 28586f3a9b6747bbbb7acc339de4b728
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442024543
status: 3
tags: []
user_id: fatsk
