artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/285b7c67cb084492985aeb1cdc5f3c33/artifacts
end_time: 1673442329601
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 285b7c67cb084492985aeb1cdc5f3c33
run_uuid: 285b7c67cb084492985aeb1cdc5f3c33
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442329530
status: 3
tags: []
user_id: fatsk
