artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/1c1f1e72aecf40fa9aff247af59bb2d0/artifacts
end_time: 1673465778374
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 1c1f1e72aecf40fa9aff247af59bb2d0
run_uuid: 1c1f1e72aecf40fa9aff247af59bb2d0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465778303
status: 3
tags: []
user_id: fatsk
