artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/698906c2a0c247659aeda4bc3abfbe9c/artifacts
end_time: 1673441971227
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 698906c2a0c247659aeda4bc3abfbe9c
run_uuid: 698906c2a0c247659aeda4bc3abfbe9c
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441971186
status: 3
tags: []
user_id: fatsk
