artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/b580c1eb3dbc4ff596314468d03f0c10/artifacts
end_time: 1673442398783
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b580c1eb3dbc4ff596314468d03f0c10
run_uuid: b580c1eb3dbc4ff596314468d03f0c10
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442398649
status: 3
tags: []
user_id: fatsk
