artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/a83f3de50f254ea4adf255f328b970c2/artifacts
end_time: 1673465701649
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a83f3de50f254ea4adf255f328b970c2
run_uuid: a83f3de50f254ea4adf255f328b970c2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465701596
status: 3
tags: []
user_id: fatsk
