artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/4250e9e792a74bdcbb19e6a08cdb28aa/artifacts
end_time: 1673465880531
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4250e9e792a74bdcbb19e6a08cdb28aa
run_uuid: 4250e9e792a74bdcbb19e6a08cdb28aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465880463
status: 3
tags: []
user_id: fatsk
