artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/b64c70d8f1b94932b6f2802a8ea30bd2/artifacts
end_time: 1673465945119
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: b64c70d8f1b94932b6f2802a8ea30bd2
run_uuid: b64c70d8f1b94932b6f2802a8ea30bd2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465945065
status: 3
tags: []
user_id: fatsk
