artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/3cc188516ab24a9ebf1a65e746692c9b/artifacts
end_time: 1673465938471
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3cc188516ab24a9ebf1a65e746692c9b
run_uuid: 3cc188516ab24a9ebf1a65e746692c9b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465938420
status: 3
tags: []
user_id: fatsk
