artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/18aed0808f2046d9a2ec540e0137a71e/artifacts
end_time: 1673465954003
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 18aed0808f2046d9a2ec540e0137a71e
run_uuid: 18aed0808f2046d9a2ec540e0137a71e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465953919
status: 3
tags: []
user_id: fatsk
