artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/152bc43dded94371b17fcf2ce69344ea/artifacts
end_time: 1673465927543
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 152bc43dded94371b17fcf2ce69344ea
run_uuid: 152bc43dded94371b17fcf2ce69344ea
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465927492
status: 3
tags: []
user_id: fatsk
