artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/055ccae120884ea08d1cb75418da5e6b/artifacts
end_time: 1673465727640
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 055ccae120884ea08d1cb75418da5e6b
run_uuid: 055ccae120884ea08d1cb75418da5e6b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465727587
status: 3
tags: []
user_id: fatsk
