artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/9cedce262aa64eda868af03e1876063d/artifacts
end_time: 1673465747425
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9cedce262aa64eda868af03e1876063d
run_uuid: 9cedce262aa64eda868af03e1876063d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465747290
status: 3
tags: []
user_id: fatsk
