artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/db9214990f6b4f14986ca13ab90ec319/artifacts
end_time: 1673442322663
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: db9214990f6b4f14986ca13ab90ec319
run_uuid: db9214990f6b4f14986ca13ab90ec319
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442322526
status: 3
tags: []
user_id: fatsk
