artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/f265aeb0933948a38c98cc418bd9a9e3/artifacts
end_time: 1673465711517
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f265aeb0933948a38c98cc418bd9a9e3
run_uuid: f265aeb0933948a38c98cc418bd9a9e3
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465711465
status: 3
tags: []
user_id: fatsk
