artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/24798e3d818f425dbff218ca5be0f9ee/artifacts
end_time: 1673465797048
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 24798e3d818f425dbff218ca5be0f9ee
run_uuid: 24798e3d818f425dbff218ca5be0f9ee
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465796904
status: 3
tags: []
user_id: fatsk
