artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/847158e0b1b047d285fd8c22b3bf5e67/artifacts
end_time: 1673465825046
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 847158e0b1b047d285fd8c22b3bf5e67
run_uuid: 847158e0b1b047d285fd8c22b3bf5e67
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465824840
status: 3
tags: []
user_id: fatsk
