artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/84f710d810c648a4bb5dd8d8dd3f706a/artifacts
end_time: 1673442193852
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 84f710d810c648a4bb5dd8d8dd3f706a
run_uuid: 84f710d810c648a4bb5dd8d8dd3f706a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442193810
status: 3
tags: []
user_id: fatsk
