artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/9d5bbec3ad484268ae55fbd3e9a46d76/artifacts
end_time: 1673442052759
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9d5bbec3ad484268ae55fbd3e9a46d76
run_uuid: 9d5bbec3ad484268ae55fbd3e9a46d76
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442052706
status: 3
tags: []
user_id: fatsk
