artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/612baad4120a4753ab56bb5f66547049/artifacts
end_time: 1673465834392
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 612baad4120a4753ab56bb5f66547049
run_uuid: 612baad4120a4753ab56bb5f66547049
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465834231
status: 3
tags: []
user_id: fatsk
