artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/c722049bbb6d4d7f8755ad4bf281e5b9/artifacts
end_time: 1673465943014
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c722049bbb6d4d7f8755ad4bf281e5b9
run_uuid: c722049bbb6d4d7f8755ad4bf281e5b9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465942880
status: 3
tags: []
user_id: fatsk
