artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/53946a0a0b1a49868f1784c938d920df/artifacts
end_time: 1673465682905
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 53946a0a0b1a49868f1784c938d920df
run_uuid: 53946a0a0b1a49868f1784c938d920df
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465682852
status: 3
tags: []
user_id: fatsk
