artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/e50fd3ef8d484da1b5a27a737f24b3c6/artifacts
end_time: 1673465914392
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e50fd3ef8d484da1b5a27a737f24b3c6
run_uuid: e50fd3ef8d484da1b5a27a737f24b3c6
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465914337
status: 3
tags: []
user_id: fatsk
