artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/84be5b4bfd55456c823a6b533541f760/artifacts
end_time: 1673442211762
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 84be5b4bfd55456c823a6b533541f760
run_uuid: 84be5b4bfd55456c823a6b533541f760
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442211718
status: 3
tags: []
user_id: fatsk
