artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/bcaa03fc827a41d5a35f9a3abe410ea9/artifacts
end_time: 1673465792329
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: bcaa03fc827a41d5a35f9a3abe410ea9
run_uuid: bcaa03fc827a41d5a35f9a3abe410ea9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465792192
status: 3
tags: []
user_id: fatsk
