artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/091e2a32bf5b4fdaa5dc22e4e907e2c1/artifacts
end_time: 1673465705868
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 091e2a32bf5b4fdaa5dc22e4e907e2c1
run_uuid: 091e2a32bf5b4fdaa5dc22e4e907e2c1
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465705815
status: 3
tags: []
user_id: fatsk
