artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/fe8cdc6b895040c39951a88b46d0c5e2/artifacts
end_time: 1673441908120
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fe8cdc6b895040c39951a88b46d0c5e2
run_uuid: fe8cdc6b895040c39951a88b46d0c5e2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441907985
status: 3
tags: []
user_id: fatsk
