artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/7409cc2abb3b46788a48740b39983f3c/artifacts
end_time: 1673465971765
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 7409cc2abb3b46788a48740b39983f3c
run_uuid: 7409cc2abb3b46788a48740b39983f3c
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465971710
status: 3
tags: []
user_id: fatsk
