artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/c584c038c40f4475bf7a1fee2dab5e1e/artifacts
end_time: 1673465933225
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c584c038c40f4475bf7a1fee2dab5e1e
run_uuid: c584c038c40f4475bf7a1fee2dab5e1e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465933177
status: 3
tags: []
user_id: fatsk
