artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/a26c233d93784e7985b58f50857ddfb9/artifacts
end_time: 1673465865954
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a26c233d93784e7985b58f50857ddfb9
run_uuid: a26c233d93784e7985b58f50857ddfb9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465865811
status: 3
tags: []
user_id: fatsk
