artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/3a88d440d89041f8817aa2dae57e7cf7/artifacts
end_time: 1673441920119
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3a88d440d89041f8817aa2dae57e7cf7
run_uuid: 3a88d440d89041f8817aa2dae57e7cf7
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441920064
status: 3
tags: []
user_id: fatsk
