artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/03cf7fe5967d4208bcdedffdb66d3b2e/artifacts
end_time: 1673442052027
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 03cf7fe5967d4208bcdedffdb66d3b2e
run_uuid: 03cf7fe5967d4208bcdedffdb66d3b2e
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442051896
status: 3
tags: []
user_id: fatsk
