artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/301dc6c0a183401d8a6a407fe76181ac/artifacts
end_time: 1673442296203
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 301dc6c0a183401d8a6a407fe76181ac
run_uuid: 301dc6c0a183401d8a6a407fe76181ac
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442296066
status: 3
tags: []
user_id: fatsk
