artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/ae8b4b89b5e3434480082df6e58a8a46/artifacts
end_time: 1673465829707
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ae8b4b89b5e3434480082df6e58a8a46
run_uuid: ae8b4b89b5e3434480082df6e58a8a46
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465829568
status: 3
tags: []
user_id: fatsk
