artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/6bcfbc21bcfa43a4bd311aae8c1f5670/artifacts
end_time: 1673442103334
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 6bcfbc21bcfa43a4bd311aae8c1f5670
run_uuid: 6bcfbc21bcfa43a4bd311aae8c1f5670
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442103291
status: 3
tags: []
user_id: fatsk
