artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/a2717e42767c44f2a0f562df67cf046f/artifacts
end_time: 1673442433041
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a2717e42767c44f2a0f562df67cf046f
run_uuid: a2717e42767c44f2a0f562df67cf046f
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442432978
status: 3
tags: []
user_id: fatsk
