artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/e98413707d3d4852bc06c73a91e9e2b4/artifacts
end_time: 1673465701970
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e98413707d3d4852bc06c73a91e9e2b4
run_uuid: e98413707d3d4852bc06c73a91e9e2b4
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465701921
status: 3
tags: []
user_id: fatsk
