artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/49d5ed79bcbb4dfd89111c0254df3475/artifacts
end_time: 1673465931534
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 49d5ed79bcbb4dfd89111c0254df3475
run_uuid: 49d5ed79bcbb4dfd89111c0254df3475
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465931480
status: 3
tags: []
user_id: fatsk
