artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/5e219beecfa4428a9abccfb34fb3b2f8/artifacts
end_time: 1673442045351
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5e219beecfa4428a9abccfb34fb3b2f8
run_uuid: 5e219beecfa4428a9abccfb34fb3b2f8
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442045214
status: 3
tags: []
user_id: fatsk
