artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/d041f0d74e7e43bbb1c8df27ee7300dd/artifacts
end_time: 1673465811051
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d041f0d74e7e43bbb1c8df27ee7300dd
run_uuid: d041f0d74e7e43bbb1c8df27ee7300dd
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465810908
status: 3
tags: []
user_id: fatsk
