artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/4da186812bc641079a712039bfdb6f89/artifacts
end_time: 1673465967365
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4da186812bc641079a712039bfdb6f89
run_uuid: 4da186812bc641079a712039bfdb6f89
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465967295
status: 3
tags: []
user_id: fatsk
