artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/0514a4e71630440b98ccfb6997a21ef8/artifacts
end_time: 1673442420263
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 0514a4e71630440b98ccfb6997a21ef8
run_uuid: 0514a4e71630440b98ccfb6997a21ef8
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442420126
status: 3
tags: []
user_id: fatsk
