artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/8423ac5d95d649ccbfcc53281725a66b/artifacts
end_time: 1673442373214
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 8423ac5d95d649ccbfcc53281725a66b
run_uuid: 8423ac5d95d649ccbfcc53281725a66b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442373077
status: 3
tags: []
user_id: fatsk
