artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/588519fdfab948578cd3516943b2807a/artifacts
end_time: 1673442179364
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 588519fdfab948578cd3516943b2807a
run_uuid: 588519fdfab948578cd3516943b2807a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442179182
status: 3
tags: []
user_id: fatsk
