artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/aacb12493b5f498a9538afea50151a90/artifacts
end_time: 1673441952674
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: aacb12493b5f498a9538afea50151a90
run_uuid: aacb12493b5f498a9538afea50151a90
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441952631
status: 3
tags: []
user_id: fatsk
