artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/38426be10cd0415dade32f795aefe849/artifacts
end_time: 1673465734771
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 38426be10cd0415dade32f795aefe849
run_uuid: 38426be10cd0415dade32f795aefe849
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465734653
status: 3
tags: []
user_id: fatsk
