artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/c2e25a671cc0466e97354c45d0f3fb24/artifacts
end_time: 1673442125957
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c2e25a671cc0466e97354c45d0f3fb24
run_uuid: c2e25a671cc0466e97354c45d0f3fb24
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442125912
status: 3
tags: []
user_id: fatsk
