artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/43b5a15afcf444b381b7dffca9408e0d/artifacts
end_time: 1673465937225
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 43b5a15afcf444b381b7dffca9408e0d
run_uuid: 43b5a15afcf444b381b7dffca9408e0d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465937164
status: 3
tags: []
user_id: fatsk
