artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/a5f23c868f594d7a9e1ae53c9936d91c/artifacts
end_time: 1673465741898
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a5f23c868f594d7a9e1ae53c9936d91c
run_uuid: a5f23c868f594d7a9e1ae53c9936d91c
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465741850
status: 3
tags: []
user_id: fatsk
