artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/707d034edbb94bfe8fee63534b20f933/artifacts
end_time: 1673442070180
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 707d034edbb94bfe8fee63534b20f933
run_uuid: 707d034edbb94bfe8fee63534b20f933
source_name: ''
source_type: 4
source_version: ''
start_time: 1673442070139
status: 3
tags: []
user_id: fatsk
