artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/1bd71029ebc24b62918c7252d25f4dde/artifacts
end_time: 1673465922444
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 1bd71029ebc24b62918c7252d25f4dde
run_uuid: 1bd71029ebc24b62918c7252d25f4dde
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465922356
status: 3
tags: []
user_id: fatsk
