artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/0/389195b8790b4b108394c83de82f07cf/artifacts
end_time: 1673441931826
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 389195b8790b4b108394c83de82f07cf
run_uuid: 389195b8790b4b108394c83de82f07cf
source_name: ''
source_type: 4
source_version: ''
start_time: 1673441931766
status: 3
tags: []
user_id: fatsk
