artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/7621cdb4ab754d9f85463f5d0f3f7c29/artifacts
end_time: 1673465938041
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 7621cdb4ab754d9f85463f5d0f3f7c29
run_uuid: 7621cdb4ab754d9f85463f5d0f3f7c29
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465937994
status: 3
tags: []
user_id: fatsk
