artifact_uri: file:///D:\00. Files\1. WIP\2. Data Analysis\MadewithML\MLOps\model/2/039f3228451f46d2ae22b8756d2c0b35/artifacts
end_time: 1673465958477
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 039f3228451f46d2ae22b8756d2c0b35
run_uuid: 039f3228451f46d2ae22b8756d2c0b35
source_name: ''
source_type: 4
source_version: ''
start_time: 1673465958399
status: 3
tags: []
user_id: fatsk
